### ISSUE TITLE
GoogleMap constructor should be called from inside isAvailable()

### ISSUE THREAD

**Issue by alexmady** [aaronksaunders/ionic2GMapNative#3]
From recent discussion on the ionic forums I understand that the following line:

`this.map = new GoogleMap('map_canvas');`

should be called after `GoogleMap.isAvailable()` resolves as follows:

```
 GoogleMap.isAvailable().then(() => {
    this.map = new GoogleMap('map_canvas');
}
```

**Comment by aaronksaunders** [comment]
thanks
