### ISSUE TITLE
Maps wont load

### ISSUE THREAD

**Issue by daCookieProject** [aaronksaunders/ionic2GMapNative#4]
Hey I implemented your example and I get the initial notfication as well as the google logo on the bottom left of the android device screen but the actual map wnt load. What could be the catch?

Edit: Found the problem. I went with the cordova prepare route and the androidManifest had an android API key different from mine although I changed config. Just install the plugin normally instead of doing cordova prepare and it should be fine!

**Comment by upuxaa** [comment]
close the issue please
