### ISSUE TITLE
 ReferenceError: plugin is not defined

### ISSUE THREAD

**Issue by mjaime1990** [aaronksaunders/ionic2GMapNative#6]
Hi, I try this example, I changed for my api key, use cordova prepare, install all dependences but when i try to run give this error: 

"Unhandled Promise rejection: plugin is not defined ; Zone: angular ; Task: Promise.then ; Value: ReferenceError: plugin is not defined(…)"

Do you have an idea how to solve this?

**Comment by arielgelbard** [comment]
same problem on my end

![screen shot 2016-08-04 at 10 04 31 am](https://cloud.githubusercontent.com/assets/5472973/17404769/e3194556-5a2a-11e6-8b7b-4ca00092ae28.png)

**Comment by aaronksaunders** [comment]
this will only work on device? Are you running on device or simulator...

**Comment by upuxaa** [comment]
@mjaime1990 are you running in chrome?

**Comment by mjaime1990** [comment]
@aaronksaunders I tryed in some browsers and my device and doesn't work, @arielgelbard nop, I have many issues in this example, but this other https://github.com/driftyco/ionic-conference-app/tree/typescript is more complete and works for me,

**Comment by aaronksaunders** [comment]
@mjaime1990 don't know what to tell you, the example has worked for many others. It sounds like you are moving on so I will close this
