### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by upuxaa** [aaronksaunders/ionic2GMapNative#7]
hey @aaronksaunders followed your instructions and I'm still getting a black screen in the iOS simulator.

1) Does this only work in the android simulator?

2) I went through the comments in the ionic forum and found this snippet; but this doesn't seem to work, any idea of how to get it working?

```
ion-app._gmaps_cdv_ .nav-decor {
    background-color: rgba(0,0,0,0) !important;
}
```

3) can you suggest a plugin or library that would allow me to use google maps and ionic for web browsers so I can serve it quicker?

![screen shot 2016-08-04 at 4 16 22 pm](https://cloud.githubusercontent.com/assets/5472973/17417192/08b27f0a-5a60-11e6-8cc0-6cd5349774f1.png)

**Comment by goduhin** [comment]
I have the same issue. Black screen.

**Comment by upuxaa** [comment]
i loaded it into the simulator / device, inspected it via safari and came to the conclusion that this is the problem for me:

```
ion-nav.has-views {
    background-color: transparent !important;
}
```

This works for me

**Comment by zefrench** [comment]
Where to write this line ?

**Comment by upuxaa** [comment]
I wrote it in app/theme/app.core.scss

**Comment by zefrench** [comment]
Thanks...
You mean here : 
// http://ionicframework.com/docs/v2/theming/

// App Shared Imports
// --------------------------------------------------
// These are the imports which make up the design of this app.
// By default each design mode includes these shared imports.
// App Shared Sass variables belong in app.variables.scss.

```
@import "../pages/page1/page1";

@import "../pages/page2/page2";

ion-nav.has-views {
    background-color: transparent !important;
}

```

It still does not work for me...

**Comment by davorpeic** [comment]
Confirming that @arielgelbard css helps remove black screen, I pasted it in app.core.scss.

@zefrench be sure to run `ionic build` so you get your sass built up too. 

![app_core_scss_ _ionic2gmapnative](https://cloud.githubusercontent.com/assets/694091/17818168/f07f2b64-6607-11e6-846b-53e9298f2def.jpg)

**Comment by aaronksaunders** [comment]
thanks for verifying this

## 

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders

This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by davorpeic** [comment]
Small update, the css provided here will patch this repo issue, but I'm using slide menu in my project, and was still getting black screen over my map, I found the issue with ionic beta.11 and the workaround can be found here https://github.com/driftyco/ionic/issues/7205

dp

**Comment by aaronksaunders** [comment]
closing this now, i have updated to latest version and of ionic with the changes mentioed by @davorpeic and it is working

**Comment by bilalsoomro** [comment]
@davorpeic Thanks a lot for sharing that. I wasted quite some time to try and figure out why my map was black on iOS.
